version: '3.8'
services:
  api:
    build: .
    container_name: api_container
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres_container
    expose:
      - 5432
    environment:
        POSTGRES_USER: pde
        POSTGRES_DB: pde
        POSTGRES_HOST : localhost
        POSTGRES_PASSWORD: pde
        POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
        - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: