# Generated by Django 4.2.5 on 2023-09-22 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='key',
            new_name='source_key',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='secret',
            new_name='source_secret',
        ),
    ]
