# Generated by Django 4.2.5 on 2023-10-04 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_source_created_at_source_updated_at_alter_source_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('properties', models.JSONField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.source')),
            ],
        ),
    ]
